"""init

Revision ID: 5841e704df01
Revises: None
Create Date: 2015-06-02 17:59:34.556162

"""

# revision identifiers, used by Alembic.
revision = '5841e704df01'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
